name: find-variable-file-in-path
description: Finds a variable in a file in the path (recursivly up) staring from current dir

inputs:
  filename:
    description: Filename of file holding the variable
    required: true
  directory:
    description: Directory from where to start seraching upwards
    required: true

outputs:
  file_contents:
    value: ${{ steps.findfile.outputs.file_contents }}

runs:
  using: composite
  steps:
    - id: findfile
      shell: bash
      run: |

        search_dir="${{ inputs.directory }}"
        echo $search_dir
        filename="${{ inputs.filename }}"

        # Initialize empty variable to store file contents
        file_contents=""

        # Check the current working directory for the file
        if [ -f "$search_dir/$filename" ]; then
          file_contents=$(cat "$search_dir/$filename")
        else
          # If the file is not found in the current directory, search for it recursively in parent directories
          while [ "$search_dir" != "/" ]; do
            if [ -f "$search_dir/$filename" ]; then
              file_contents=$(cat "$search_dir/$filename")
              break
            fi
            search_dir=$(dirname "$search_dir")
          done
        fi

        # Check if the file was found
        echo "file-contents"
        echo $file_contents

        if [ ! -z "$file_contents" ]; then
          echo "::set-output file_contents=$file_contents" >> $GITHUB_OUTPUT
        else
          echo "::set-output file_contents=" >> $GITHUB_OUTPUT
        fi