name: setup-gitleaks
description: Installs gitleaks (linux x64)

inputs:
  version:
    description: Version, e.g. '8.16.3'
    required: true

runs:
  using: composite
  steps:
    - id: setup
      shell: bash
      run: |
          ## Download gitleaks & checksums
          curl -fsSLO "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" && \
          curl -fsSLO "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_checksums.txt"

          ### verify checksum
          grep -e  "gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" "gitleaks_${GITLEAKS_VERSION}_checksums.txt" | sha256sum -c

          tar zxvf "gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
          chmod +x gitleaks

          tmp_bin_dir="$(mktemp -d $RUNNER_TEMP/XXXXXXXXXX)"
          gitleaks_bin="$tmp_bin_dir/gitleaks"
          mv gitleaks $gitleaks_bin
          echo "$tmp_bin_dir" >> $GITHUB_PATH

      env:
        GITLEAKS_VERSION: ${{ inputs.version }}
